### ISSUE TITLE
Show the process

### ISSUE THREAD

**Issue by odyright** [kwongtailau/StudentManagementSystem#1]
Hello your project sems good, great work. I'm not familiar with C# application, can you show us the way to run your application?
thanks

**Comment by kwongtailau** [comment]
Sorry for replying you late. The steps how to run my code is update in [`README.md`](https://github.com/kwongtailau/StudentManagementSystem).  My work has some bugs, and still has many functions to be completed future. If can, please give issues or PR. Thanks!
